### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/MethodOfLines.jl#41]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by xtalax** [comment]
@JuliaRegistrator register()

**Comment by xtalax** [comment]
@ChrisRackauckas ^

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
You should have access by being on the PDE team?

**Comment by xtalax** [comment]
I would have thought so, but apparently not

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by xtalax** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
You changed the version?

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by xtalax** [comment]
@JuliaRegistrator register()

**Comment by xtalax** [comment]
@JuliaRegistrator register()

**Comment by xtalax** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by xtalax** [comment]
@JuliaRegistrator register()

**Comment by xtalax** [comment]
@JuliaRegistrator register()

**Comment by xtalax** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register

  Release notes:

  # MethodOfLines.jl v1.0

  MethodOfLines v1.0 makes symbolic compilation O(1) with respect to the number of grid points when using a `DAEProblem`. This can make compilation orders of magnitude faster than before, so `DAEProblem` is now the default for time-dependent systems.

  ```julia
  prob = discretize(pdesys, discretization)
  sol = solve(prob)
  ```

  This scaling improvement does not apply to `ODEProblem`, because compiling one scalarizes the equations. Explicit Runge–Kutta methods such as `Tsit5()` and `SSPRK54()` therefore require the explicit ODE path:

  ```julia
  sys, tspan = symbolic_discretize(pdesys, discretization)
  prob = ODEProblem(mtkcompile(sys), nothing, tspan)
  sol = solve(prob, Tsit5())
  ```

  Time-independent systems continue to return `NonlinearProblem`. Solutions remain wrapped as `PDETimeSeriesSolution`, with unchanged PDE-variable indexing and interpolation.

**Comment by ChrisRackauckas-Claude** [comment]
@JuliaRegistrator register

Release notes:

# MethodOfLines.jl v1.0

## Breaking changes

`discretize` now returns a `DAEProblem` by default for time-dependent systems. This keeps the symbolic equation count independent of the number of spatial grid points and can make compilation orders of magnitude faster than the pre-v1 `ODEProblem` path.

```julia
prob = discretize(pdesys, discretization)
sol = solve(prob)
```

Code that passes an explicit Runge–Kutta method directly to the result of `discretize`, such as `solve(prob, Tsit5())`, must instead construct an `ODEProblem` explicitly:

```julia
sys, tspan = symbolic_discretize(pdesys, discretization)
prob = ODEProblem(mtkcompile(sys), nothing, tspan)
sol = solve(prob, Tsit5())
```

This explicit ODE path scalarizes the equations and therefore does not receive the new compilation scaling.

The system returned by `symbolic_discretize` now uses symbolic array equations rather than one scalar equation per grid point. Code that directly inspects or transforms those equations may need to be updated.

Time-independent systems continue to return `NonlinearProblem`. Solutions remain wrapped as `PDETimeSeriesSolution`, with unchanged PDE-variable indexing and interpolation.
