### ISSUE TITLE
Finalize upwinding in MOLFiniteDifference

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/MethodOfLines.jl#7]
This requires a rule application so that the substitution can look for an arbitrary `a *D(u)` and rewrite with `a` . Almost working code is there as a comment:

```julia
        forward_weights(i,j) = DiffEqOperators.calculate_weights(discretization.upwind_order, 0.0, [space[j][i[j]],space[j][i[j]+1]])
        reverse_weights(i,j) = DiffEqOperators.calculate_weights(discretization.upwind_order, 0.0, [space[j][i[j]-1],space[j][i[j]]])
        upwinding_rules = [@rule(*(~~a,(Differential(nottime[j]))(u),~~b) => IfElse.ifelse(*(~~a..., ~~b...,)>0,
                                *(~~a..., ~~b..., dot(reverse_weights(i,j),depvars[k][central_neighbor_idxs(i,j)[1:2]])),
                                *(~~a..., ~~b..., dot(forward_weights(i,j),depvars[k][central_neighbor_idxs(i,j)[2:3]]))))
                                for j in 1:length(nottime), k in 1:length(pdesys.depvars)]
```

but this requires an additional feature in the SymbolicUtils rules for interpolation into rules.

@shashi @YingboMa

**Comment by xtalax** [comment]
I'm working on this now, trying to ensure that upwind differences are only using the correct boundary conditions. The problem is that depending on the winding direction different BCs will be used. I can capture this with `IfElse`, true including an interior equation and false including the BC, but this raises an issue if there are higher order derivative terms which might need the boundary equation. 

How do I ensure that the system is not overdetermined? One solution might be to substitute in boundary equations where needed by solving for the ghost node premptively, but this limits boundary conditions to being linear as this is all `Symbolics.solve_for` can handle.

An alternative might be to reduce the size of the interior, as mentioned here: https://github.com/SciML/DiffEqOperators.jl/pull/382#issuecomment-828728351

**Comment by xtalax** [comment]
This turned out to be a non issue, Upwinding now works at  first order but there is still instability at higher order
